export const fieldTypes = [
    {
        "key": "createdBy",
        "name": "创建人",
        "type": "System",
        "dataType": "object",
        "disabled": false,
        "component": "CreatedBy",
        "defaultKey": "createdBy",
        "description": "创建人",
        "objectId": "1g5POUEzw9"
    },
    {
        "key": "Radio",
        "name": "单选",
        "type": "Custom",
        "dataType": "string",
        "disabled": false,
        "component": "Radio",
        "defaultKey": "Radio",
        "description": "单选按钮",
        "objectId": "3wIfFg5kx4"
    },
    {
        "key": "Editor",
        "name": "编辑器",
        "type": "Custom",
        "dataType": "object",
        "disabled": false,
        "component": "Editor",
        "defaultKey": "Editor",
        "description": "支持富文本格式内容的输入组件",
        "objectId": "4DFeBwRLk9"
    },
    {
        "key": "Cascade",
        "name": "级联",
        "type": "Custom",
        "dataType": "array",
        "disabled": false,
        "property": {},
        "component": "Cascade",
        "defaultKey": "Cascade",
        "description": "级联字段类型",
        "objectId": "5EXG80C96P"
    },
    {
        "key": "Tag",
        "name": "标签",
        "type": "Custom",
        "dataType": "array",
        "disabled": false,
        "component": "Tag",
        "defaultKey": "Tag",
        "description": "支持添加、多选",
        "objectId": "5nYmdVook2"
    },
    {
        "key": "Version",
        "name": "版本（系统）",
        "type": "System",
        "dataType": "array",
        "disabled": false,
        "component": "Version",
        "configurable": true,
        "defaultKey": "Version",
        "description": "所属版本",
        "objectId": "6Yp5cemCOS"
    },
    {
        "key": "Tree",
        "name": "树形组件",
        "type": "Custom",
        "dataType": "array",
        "disabled": false,
        "component": "Tree",
        "defaultKey": "Tree",
        "description": "树形组件",
        "objectId": "6zyovxNVuQ"
    },
    {
        "key": "LongText",
        "name": "长文本",
        "type": "Custom",
        "dataType": "string",
        "disabled": false,
        "component": "LongText",
        "defaultKey": "LongText",
        "description": "仅允许输入单行或多行文本的输入框",
        "objectId": "9SZARgA5TI"
    },
    {
        "key": "User",
        "name": "用户",
        "type": "Custom",
        "dataType": "array",
        "disabled": false,
        "component": "User",
        "defaultKey": "User",
        "description": "支持选择一个或多个用户的下拉列表",
        "objectId": "AG5wBe2Ir0"
    },
    {
        "key": "DataQuote",
        "name": "数据引用",
        "type": "Custom",
        "dataType": "array",
        "disabled": false,
        "component": "DataQuote",
        "defaultKey": "DataQuote",
        "description": "数据引用",
        "objectId": "ALrRtpfK1B"
    },
    {
        "key": "StoryPoint",
        "name": "故事点",
        "type": "System",
        "dataType": "number",
        "disabled": false,
        "component": "StoryPoint",
        "defaultKey": "StoryPoint",
        "description": "故事点",
        "objectId": "CpJDd7io5a"
    },
    {
        "key": "HyperLink",
        "name": "超链接",
        "type": "Custom",
        "dataType": "string",
        "disabled": false,
        "component": "HyperLink",
        "defaultKey": "HyperLink",
        "description": "超链接字段",
        "objectId": "DD20Erqqnq"
    },
    {
        "key": "Team",
        "name": "团队",
        "type": "System",
        "dataType": "array",
        "disabled": false,
        "component": "Team",
        "defaultKey": "Team",
        "description": "团队插件字段类型",
        "objectId": "DgBnXFOc2P"
    },
    {
        "key": "StatusType",
        "name": "状态类型",
        "type": "System",
        "dataType": "array",
        "disabled": false,
        "component": "StatusType",
        "defaultKey": "StatusType",
        "description": "状态类型",
        "objectId": "EPBm2adxxk"
    },
    {
        "key": "ItemType",
        "name": "类型",
        "type": "System",
        "dataType": "string",
        "disabled": false,
        "component": "ItemType",
        "defaultKey": "ItemType",
        "description": "用于选择事项类型的下拉列表",
        "objectId": "HBZegUsQdF"
    },
    {
        "key": "File",
        "name": "文件",
        "type": "Custom",
        "dataType": "array",
        "disabled": false,
        "component": "File",
        "defaultKey": "File",
        "objectId": "IIk9yCrWC5"
    },
    {
        "key": "Workspace",
        "name": "空间",
        "type": "System",
        "dataType": "string",
        "disabled": false,
        "component": "Workspace",
        "defaultKey": "Workspace",
        "description": "用于选择空间的下拉列表",
        "objectId": "IJ9nXcXYKB"
    },
    {
        "key": "updatedBy",
        "name": "修改人",
        "type": "System",
        "dataType": "object",
        "disabled": false,
        "component": "UpdatedBy",
        "defaultKey": "updatedBy",
        "description": "修改人",
        "objectId": "IKeDQI8CrC"
    },
    {
        "key": "Reporter",
        "name": "报告人",
        "type": "System",
        "dataType": "array",
        "disabled": false,
        "component": "Reporter",
        "defaultKey": "Reporter",
        "description": "报告人",
        "objectId": "Idh8D5b4sF5"
    },
    {
        "key": "Name",
        "name": "事项标题",
        "type": "System",
        "dataType": "string",
        "disabled": false,
        "component": "Name",
        "defaultKey": "Name",
        "description": "用于输入事项标题的单行文本框",
        "objectId": "NTXX60ceoD"
    },
    {
        "key": "BindWorkspace",
        "name": "绑定空间",
        "type": "Custom",
        "dataType": "string",
        "disabled": false,
        "component": "BindWorkspace",
        "defaultKey": "BindWorkspace",
        "objectId": "TZwrcPvByG"
    },
    {
        "key": "Formula",
        "name": "公式",
        "type": "Custom",
        "dataType": "string",
        "disabled": false,
        "component": "Formula",
        "defaultKey": "Formula",
        "description": "支持字段之间的运算",
        "objectId": "XDAHTRGVzH"
    },
    {
        "key": "Priority",
        "name": "优先级",
        "type": "System",
        "dataType": "string",
        "disabled": false,
        "component": "Priority",
        "defaultKey": "Priority",
        "description": "优先级",
        "objectId": "YE5NQcNDAn"
    },
    {
        "key": "UserGroup",
        "name": "用户组",
        "type": "Custom",
        "dataType": "array",
        "disabled": false,
        "component": "UserGroup",
        "defaultKey": "UserGroup",
        "description": "用户组",
        "objectId": "an27WsuEID"
    },
    {
        "key": "Date",
        "name": "日期",
        "type": "Custom",
        "dataType": "number",
        "disabled": false,
        "component": "Date",
        "defaultKey": "Date",
        "description": "仅允许输入或选择日期的输入框",
        "objectId": "cFdABEFcts"
    },
    {
        "key": "updatedAt",
        "name": "修改时间",
        "type": "System",
        "dataType": "string",
        "disabled": false,
        "component": "UpdatedAt",
        "defaultKey": "updatedAt",
        "description": "修改时间",
        "objectId": "euBEAkKOz0"
    },
    {
        "key": "Assignee",
        "name": "负责人",
        "type": "System",
        "dataType": "array",
        "disabled": false,
        "component": "Assignee",
        "defaultKey": "Assignee",
        "description": "负责人",
        "objectId": "f59j6P7DhC"
    },
    {
        "key": "ItemLevel",
        "name": "事项层级",
        "type": "System",
        "dataType": "array",
        "disabled": false,
        "component": "ItemLevel",
        "defaultKey": "ItemLevel",
        "description": "事项层级",
        "objectId": "gJxcU0Vy8o"
    },
    {
        "key": "Checkbox",
        "name": "复选",
        "type": "Custom",
        "dataType": "array",
        "disabled": false,
        "component": "Checkbox",
        "defaultKey": "Checkbox",
        "description": "支持多选的复选框",
        "objectId": "iW2i992pSp"
    },
    {
        "key": "EarlyWarning",
        "name": "预警",
        "type": "System",
        "dataType": "object",
        "disabled": false,
        "property": {},
        "defaultKey": "EarlyWarning",
        "description": "预警字段类型",
        "objectId": "jGXxAc32dP"
    },
    {
        "key": "Script",
        "name": "脚本",
        "type": "Custom",
        "dataType": "string",
        "disabled": false,
        "component": "Script",
        "defaultKey": "Script",
        "description": "脚本",
        "objectId": "lOEItOxsUu"
    },
    {
        "key": "Text",
        "name": "文本",
        "type": "Custom",
        "dataType": "string",
        "disabled": false,
        "component": "Text",
        "defaultKey": "Text",
        "description": "仅允许输入单行文本的输入框",
        "objectId": "na20LzXTA2"
    },
    {
        "key": "Key",
        "name": "key",
        "type": "System",
        "dataType": "string",
        "disabled": false,
        "component": "Key",
        "defaultKey": "Key",
        "objectId": "pN1urEY45D"
    },
    {
        "key": "Dropdown",
        "name": "下拉选项",
        "type": "Custom",
        "dataType": "array",
        "disabled": false,
        "component": "Dropdown",
        "defaultKey": "Dropdown",
        "description": "支持选择一个或多个选项的下拉列表",
        "objectId": "pgCBxAIJjG"
    },
    {
        "key": "Link",
        "name": "事项关联",
        "type": "System",
        "dataType": "object",
        "disabled": false,
        "component": "Link",
        "defaultKey": "Link",
        "description": "事项关联",
        "objectId": "pmtLzwTuwd"
    },
    {
        "key": "Sprint",
        "name": "迭代",
        "type": "Custom",
        "sourceAppKey": "scrum",
        "dataType": "array",
        "disabled": true,
        "property": {},
        "component": "Sprint",
        "defaultKey": "Sprint",
        "description": "所属迭代",
        "objectId": "rETqSrEpjZ"
    },
    {
        "key": "Status",
        "name": "状态",
        "type": "System",
        "dataType": "object",
        "disabled": false,
        "component": "Status",
        "defaultKey": "Status",
        "description": "用于流程状态显示",
        "objectId": "voZko9nkcn"
    },
    {
        "key": "Number",
        "name": "数值",
        "type": "Custom",
        "dataType": "number",
        "disabled": false,
        "component": "Number",
        "defaultKey": "Number",
        "description": "仅允许输入数值的输入框",
        "objectId": "xCY9ooDKKY"
    },
    {
        "key": "createdAt",
        "name": "创建时间",
        "type": "System",
        "dataType": "string",
        "disabled": false,
        "component": "CreatedAt",
        "defaultKey": "createdAt",
        "description": "创建时间",
        "objectId": "xCv93s1xut"
    },
    {
        "key": "CustomVersion",
        "name": "版本（自定义）",
        "type": "Custom",
        "dataType": "array",
        "disabled": false,
        "component": "Version",
        "defaultKey": "CustomVersion",
        "description": "所属版本",
        "objectId": "yCE1bJNxOU"
    }
]
